//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITHANHTOAN
    {
        public string MALOAITHANHTOAN { get; set; }
        public string TENLOAITHANHTOAN { get; set; }
        public Nullable<double> GIATIEN { get; set; }
    }
}
