//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        public string MAPHIM { get; set; }
        public string TENTHELOAI { get; set; }
        public string TENPHIM { get; set; }
        public string VIDEO { get; set; }
        public string HINHANH { get; set; }
        public string INFO { get; set; }
    
        public virtual THELOAI THELOAI { get; set; }
    }
}
